name: Auto Merge inv to dev

permissions:
  contents: write

on:
  push:
    branches:
      - dev

jobs:
  merge_to_dev:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0  # Ensures history is available for merging

      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install gcc
      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v1.1
      - name: Install Visual Studio
        uses: egor-tensin/setup-msvc@v1
        with:
          version: vs2022

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
          default: true
          profile: minimal
          override: true    

      - name: Build with MSBuild
        run: msbuild MyProject.sln /p:Configuration=Release /p:Platform="x64"
      
      - name: Build project
        run: g++ -o hello_world main.cpp
      - name: Run tests
        run: ./hello_world
      
