name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - try
  pull_request:
    branches:
      - try

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
  QT_PATH: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\Qt\6.6.1\msvc2019_64
  QtMsBuild: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\QtMsBuild
  QtToolsPath: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\Qt\6.6.1\msvc2019_64\bin

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the main project repository
        uses: actions/checkout@v4
        with:
          repository: OT-OpenTwin/OpenTwin
          ref: Ci
          path: OpenTwin

     
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'false'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--external 7z'

      - name: Install Qt Visual Studio Tools Extension
        shell: powershell
        run: |
          $vsixPath = "$env:TEMP\QtVsTools.vsix"
          Invoke-WebRequest -Uri "https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix" -OutFile $vsixPath
          & "$env:DEVENV_PATH\devenv.exe" /InstallVSPackage "$vsixPath"

      - name: Verify Qt Visual Studio Tools Installation
        shell: powershell
        run: |
          $extensionsPath = "$env:LOCALAPPDATA\Microsoft\VisualStudio\17.0_*\Extensions"
          $qtExtension = Get-ChildItem -Path $extensionsPath -Recurse | Where-Object { $_.Name -eq "qtvs" }
          if ($qtExtension) {
            Write-Host "Qt Visual Studio Tools installed successfully."
          } else {
            Write-Host "Qt Visual Studio Tools installation failed."
            exit 1
          }

      - name: Set Environment Variables for Qt and MSBuild
        shell: powershell
        run: |
          $env:PATH="$env:QtToolsPath;$env:QtMsBuild;$env:PATH"
          Write-Output "QT_PATH=$env:QT_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "QtMsBuild=$env:QtMsBuild" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "QtToolsPath=$env:QtToolsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Environment variables set."

      - name: Configure Qt in Visual Studio
        shell: powershell
        run: |
          $qtPath = $env:QT_PATH
          if (Test-Path $qtPath) {
            & "${env:DEVENV_PATH}\Extensions\QtVS\qtversion.exe" -add 6.6.1 $qtPath
            Write-Host "Qt version configured in Visual Studio."
          } else {
            Write-Host "QT_PATH does not exist: $qtPath"
            exit 1
          }

      - name: Setup and Execute Build
        shell: cmd
        run: |
          echo "Current directory: %cd%"
          set OPENTWIN_DEV_ROOT=%cd%\OpenTwin
          set DEVENV_ROOT_2022=%DEVENV_PATH%
          set OPENTWIN_THIRDPARTY_ROOT=%cd%\ThirdParty
          echo "OPENTWIN_DEV_ROOT=%OPENTWIN_DEV_ROOT%"
          echo "DEVENV_ROOT_2022=%DEVENV_ROOT_2022%"
          echo "OPENTWIN_THIRDPARTY_ROOT=%OPENTWIN_THIRDPARTY_ROOT%"
          echo "Checking directories and necessary files..."
          echo "OpenTwin directory: %OPENTWIN_DEV_ROOT%"
          dir %OPENTWIN_DEV_ROOT%
          echo "ThirdParty directory: %OPENTWIN_THIRDPARTY_ROOT%"
          dir %OPENTWIN_THIRDPARTY_ROOT%
          echo "Visual Studio 2022 directory: %DEVENV_ROOT_2022%"
          dir "%DEVENV_ROOT_2022%"
          echo "Checking if BuildAll.bat exists..."
          if exist %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat (
            echo "Starting BuildAll.bat..."
            call %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat 
          ) else (
            echo "BuildAll.bat not found."
            exit /b 1
          )

      - name: Verify the Build
        shell: cmd
        run: |
          echo "Verifying build..."
          if exist %OPENTWIN_DEV_ROOT%\path\to\your\output\binary.exe (
            echo "Build successful."
          ) else (
            echo "Build failed."
            exit /b 1
          )
