name: Dockerized C++ Build

on:
  push:
    branches: [ Docker_Implementation ]  # Adjust branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t cpp-build-env .

      - name: Run Docker container
        run: docker run --name my-cpp-build-container -v ${{ github.workspace }}:/project -d cpp-build-env

      - name: Execute build process inside Docker container
        run: |
          docker exec my-cpp-build-container bash -c "cd /project && cmake -B . -S . && cmake --build . --config Release"

      - name: Extract build artifacts
        run: docker cp my-cpp-build-container:/project/build/main.exe ${{ github.workspace }}/main.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: main.exe
