name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - try
  pull_request:
    branches:
      - try

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
  QT_PATH: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\Qt\6.6.1\msvc2019_64
  QtMsBuild: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\QtMsBuild
  QtToolsPath: D:\a\cpp-hello-world\cpp-hello-world\ThirdParty\Qt\6.6.1\msvc2019_64\bin

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the main project repository
        uses: actions/checkout@v4
        with:
          repository: OT-OpenTwin/OpenTwin
          ref: Ci
          path: OpenTwin

      - name: Check out the ThirdParty repository
        uses: actions/checkout@v4
        with:
          repository: OT-OpenTwin/ThirdParty
          ref: main
          path: ThirdParty

      - name: Add Visual Studio to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'false'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--external 7z'

      - name: Set Environment Variables for Qt and MSBuild
        shell: powershell
        run: |
          $env:PATH="$env:QtToolsPath;$env:QtMsBuild;$env:PATH"
          Write-Output "QT_PATH=$env:QT_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "QtMsBuild=$env:QtMsBuild" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "QtToolsPath=$env:QtToolsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Output "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Environment variables set."

      - name: Configure Qt in Visual Studio
        shell: cmd
        run: |
          set QTDIR=%QT_PATH%
          "%DEVENV_PATH%\Extensions\QtVS\qtversion.exe" -add 6.6.1 %QTDIR%

      - name: Setup and Execute Build
        shell: cmd
        run: |
          echo "Current directory: %cd%"
          set OPENTWIN_DEV_ROOT=%cd%\OpenTwin
          set DEVENV_ROOT_2022=%DEVENV_PATH%
          set OPENTWIN_THIRDPARTY_ROOT=%cd%\ThirdParty
          echo "OPENTWIN_DEV_ROOT=%OPENTWIN_DEV_ROOT%"
          echo "DEVENV_ROOT_2022=%DEVENV_ROOT_2022%"
          echo "OPENTWIN_THIRDPARTY_ROOT=%OPENTWIN_THIRDPARTY_ROOT%"
          echo "Checking directories and necessary files..."
          echo "OpenTwin directory: %OPENTWIN_DEV_ROOT%"
          dir %OPENTWIN_DEV_ROOT%
          echo "ThirdParty directory: %OPENTWIN_THIRDPARTY_ROOT%"
          dir %OPENTWIN_THIRDPARTY_ROOT%
          echo "Visual Studio 2022 directory: %DEVENV_ROOT_2022%"
          dir "%DEVENV_ROOT_2022%"
          echo "Checking if BuildAll.bat exists..."
          if exist %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat (
            echo "Starting BuildAll.bat..."
            call %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat 
          ) else (
            echo "BuildAll.bat not found."
            exit /b 1
          )

      - name: Verify the Build
        shell: cmd
        run: |
          echo "Verifying build..."
          if exist %OPENTWIN_DEV_ROOT%\path\to\your\output\binary.exe (
            echo "Build successful."
          ) else (
            echo "Build failed."
            exit /b 1
          )
