name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - try
  pull_request:
    branches:
      - try

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the main project repository
        uses: actions/checkout@v4
        with:
          repository: OT-OpenTwin/OpenTwin
          ref: Ci
          path: OpenTwin

      - name: Check out the ThirdParty repository
        uses: actions/checkout@v4
        with:
          repository: OT-OpenTwin/ThirdParty
          path: ThirdParty

      - name: Add Visual Studio to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Set QTDIR and QtToolsPath
        shell: bash
        run: |
          export QTDIR=$GITHUB_WORKSPACE/ThirdParty/Qt/6.6.1/msvc2019_64
          export QtToolsPath=$QTDIR/bin
          echo "QTDIR=$QTDIR" >> "$GITHUB_ENV"
          echo "QtToolsPath=$QtToolsPath" >> "$GITHUB_ENV"
          echo "Path=$QtToolsPath:$PATH" >> "$GITHUB_ENV"

      - name: Verify Qt Setup
        shell: bash
        run: |
          echo "Verifying Qt setup..."
          if [ -z "$QTDIR" ]; then
            echo "QTDIR is not set."
            exit 1
          fi
          if ! command -v $QtToolsPath/qmake &> /dev/null; then
            echo "qmake could not be found"
            exit 1
          fi
          if ! command -v $QtToolsPath/moc &> /dev/null; then
            echo "moc could not be found"
            exit 1
          fi
          if ! command -v $QtToolsPath/uic &> /dev/null; then
            echo "uic could not be found"
            exit 1
          fi
          echo "Qt setup verified successfully."

      - name: Setup and Execute Build
        shell: cmd
        run: |
          echo "Current directory: %cd%"
          set OPENTWIN_DEV_ROOT=%cd%\OpenTwin
          set DEVENV_ROOT_2022=%DEVENV_PATH%
          set OPENTWIN_THIRDPARTY_ROOT=%cd%\ThirdParty
          echo "OPENTWIN_DEV_ROOT=%OPENTWIN_DEV_ROOT%"
          echo "DEVENV_ROOT_2022=%DEVENV_ROOT_2022%"
          echo "OPENTWIN_THIRDPARTY_ROOT=%OPENTWIN_THIRDPARTY_ROOT%"
          echo "Checking directories and necessary files..."
          echo "OpenTwin directory: %OPENTWIN_DEV_ROOT%"
          dir %OPENTWIN_DEV_ROOT%
          echo "ThirdParty directory: %OPENTWIN_THIRDPARTY_ROOT%"
          dir %OPENTWIN_THIRDPARTY_ROOT%
          echo "Visual Studio 2022 directory: %DEVENV_ROOT_2022%"
          dir "%DEVENV_ROOT_2022%"
          echo "Checking if BuildAll.bat exists..."
          if exist %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat (
            echo "Starting BuildAll.bat..."
            call %OPENTWIN_DEV_ROOT%\Scripts\BuildAndTest\BuildAll.bat 
          ) else (
            echo "BuildAll.bat not found."
            exit /b 1
          )
