name: Build and Push Docker Image

on:
  push:
    branches:
      - Docker_Implementation  # Adjust the branch as needed

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t Reeva30/try:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-username/your-image-name:latest
