name: Build and Test C++ Project

on:
  push:
    branches:
      - try  # Adjust the branch as needed

jobs:
  build-and-test:
    runs-on: windows-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 2022

    - name: Install Qt Visual Studio Tools extension
      run: |
        $ErrorActionPreference = 'Stop'
        Invoke-WebRequest -Uri "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/qtproject/vsextensions/vstools/2.9.3/vspackage" -OutFile "QtVsTools.vsix"
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --addProductLang QtVsTools.vsix --quiet --wait


