name: Build and Push Docker Image

on:
  push:
    branches:
      - Docker_Implementation  # Adjust the branch as needed

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          choco install docker-cli
          Start-Service docker

      - name: Build Docker image
        run: |
          docker build -t reeva30/try:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push reeva30/try:latest
