name: C++ Build and Test

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]


jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install CMake using Chocolatey
      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell

      # Install Visual Studio 2022 Build Tools
      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        shell: powershell

      # Set up Visual Studio command-line environment
      - name: Set up Visual Studio Build Environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      # Ensure that the -S (source) flag points to the root (or subdirectory with CMakeLists.txt)
      - name: Generate Build Files
        run: |
          cmake -S . -B build

      # Ensure the build folder is correct
      - name: Build Project
        run: |
          cmake --build build --config Release


      # Run the executable
      - name: Run the executable
        run: |
          .\build\Release\main.exe
