name: Setup Qt Environment on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_qt_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '2022'

      - name: Install Visual Studio 2022 Build Tools
        run: |
          # Install Visual Studio 2022 Build Tools
          choco install visualstudio2022buildtools --version=17.0.3 --yes
          # Install necessary components
          & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\BuildTools" --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --wait
        shell: powershell

      - name: Install Qt
        run: |
          choco install qt --version=5.15.2 --yes
        shell: powershell

      - name: Set up Qt environment variables
        run: |
          $QtPath = "C:\Qt\5.15.2\msvc2019_64"
          echo "QTDIR=$QtPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "PATH=$QtPath\bin;$Env:PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "QT_PLUGIN_PATH=$QtPath\plugins" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "QML2_IMPORT_PATH=$QtPath\qml" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Verify Qt installation
        run: |
          & $Env:QTDIR\bin\qmake -v
        shell: powershell

