name: Simplified C++ Build and Test

on:
  push:
    branches: [inv]
  pull_request:
    branches: [inv]

jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Visual Studio 2022 Build Tools using Chocolatey
      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Workload.NativeDesktop"
          if ($LASTEXITCODE -eq 3010) {
            # Ignore the reboot required error code and continue
            Write-Host "Reboot requested by the installer. Ignoring and continuing."
            $LASTEXITCODE = 0
          }
        shell: powershell
        continue-on-error: true

      # Install Rust (v1.76.0)
      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      # Verify Rust Installation
      - name: Verify Rust Installation
        run: |
          rustc --version
      
      # Set up the Visual Studio Build Environment
      - name: Set up Visual Studio Build Environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Add QT Visual Studio Tools
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" --add Microsoft.VisualStudio.Component.QT.VisualStudioTools --quiet

      # Build project using MSBuild
      - name: Build Project
        shell: cmd
        run: |
          MSBuild YourSolution.sln /p:Configuration=Release /p:Platform="x64"

      # Run the resulting executable
      - name: Run the executable
        run: |
          Join-Path -Path $PWD -ChildPath "build\main.exe"
