name: Hello World CI

on:
  # Trigger CI on push and pull request
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup MSVC (Visual Studio Build Tools)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build C++ Code
        run: |
          cl /EHsc main.cpp /Fe:main.exe

      - name: List Directory Contents (Debugging)
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
