name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_PATH: ${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the main project repository
      uses: actions/checkout@v4
      with:
        repository: OT-OpenTwin/OpenTwin
        ref: Ci
        path: OpenTwin


    - name: Add Visual Studio to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Set Up Qt Environment
      run: |
        $qtPath = "C:\\Qt\\6.6.1\\msvc2019_64"
        [Environment]::SetEnvironmentVariable("QTDIR", $qtPath, [System.EnvironmentVariableTarget]::Machine)
        [Environment]::SetEnvironmentVariable("Path", "$($env:Path);$qtPath\\bin", [System.EnvironmentVariableTarget]::Machine)
      shell: powershell

    - name: Verify Qt Setup
      run: |
        echo "Verifying Qt setup..."
        if (-Not $env:QTDIR) {
          Write-Error "QTDIR is not set."
          exit 1
        }
        if (-Not (Get-Command qmake -ErrorAction SilentlyContinue)) {
          Write-Error "qmake is not found in PATH."
          exit 1
        }
        if (-Not (Get-Command moc -ErrorAction SilentlyContinue)) {
          Write-Error "moc is not found in PATH."
          exit 1
        }
        if (-Not (Get-Command uic -ErrorAction SilentlyContinue)) {
          Write-Error "uic is not found in PATH."
          exit 1
        }
        echo "Qt setup verified successfully."
      shell: powershell
