name: Hello World CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version

      - name: Setup MSBuild and Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Verify MSVC Compiler (`cl`)
        shell: cmd
        run: |
          cl /?

      - name: Build C++ Code
        shell: cmd
        run: |
          cl /EHsc main.cpp /Fe:main.exe

      - name: List Directory Contents (Debugging)
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
