name: MSBuild

on:
  push:
    branches: [ "AWSDemo" ]
  pull_request:
    branches: [ "AWSDemo" ]

env:
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_PATH: C:\Qt\6.6.1\msvc2019_64
  QT_MSBUILD: C:\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the main project repository
    - name: Check out the main project repository
      uses: actions/checkout@v2
      with:
        repository: OT-OpenTwin/OpenTwin
        ref: Ci
        path: OpenTwin

   

    # Step 3: Install Rust 1.76.0
    - name: Install Rust 1.76.0
      run: |
        choco install rust --version=1.76.0 -y
      shell: cmd

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Add Visual Studio to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Debug - List repository files
      run: dir /s
      shell: cmd

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify the version you need

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
      
    # Install Python and Sphinx
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Sphinx and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme

    - name: Setup and Execute Build
      shell: cmd
      run: |
        echo "Current directory: %cd%"
        set OPENTWIN_DEV_ROOT=%cd%\OpenTwin
        set DEVENV_ROOT_2022=%DEVENV_PATH%
        set QT_ROOT_DIR=%RUNNER_WORKSPACE%\Qt\6.6.1\win64_msvc2019_64
        set PATH=%QT_ROOT_DIR%\bin;%PATH%
        set QTDIR=%QT_ROOT_DIR%
        set QMAKESPEC=win32-msvc
        set QT_PLUGIN_PATH=%QT_ROOT_DIR%\plugins
        echo "OPENTWIN_DEV_ROOT=%OPENTWIN_DEV_ROOT%"
        echo "DEVENV_ROOT_2022=%DEVENV_ROOT_2022%"
        echo "Checking directories and necessary files..."
        echo "OpenTwin directory: %OPENTWIN_DEV_ROOT%"
        dir %OPENTWIN_DEV_ROOT%
        echo "Visual Studio 2022 directory: %DEVENV_ROOT_2022%"
        dir "%DEVENV_ROOT_2022%"
        echo "Qt directory: %QT_ROOT_DIR%"
        dir "%QT_ROOT_DIR%"
        echo "Checking if BuildAll.bat exists..."
        echo "Starting BuildAll.bat..."
        "%DEVENV_ROOT_2022%\devenv.com" "%OPENTWIN_DEV_ROOT%\Libraries\OTWidgets\OTWidgets.vcxproj" %TYPE% "Debug|x64"
        echo "All checks passed."


  
