name: Install Qt VS Add-in and Integrate with Visual Studio 2022

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  setup-qt-vsaddin:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Verify Visual Studio 2022 installation
      run: |
        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        if (-Not (Test-Path $vswherePath)) {
          Write-Error "vswhere.exe not found. Visual Studio 2022 might not be installed."
          exit 1
        }
        $vsInstallPath = & $vswherePath -latest -version "[17.0,18.0)" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        Write-Output "VS_INSTALL_PATH=$vsInstallPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Download Qt VS Add-in
      run: |
        $url = "https://mirror.netcologne.de/qtproject/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix"
        $output = "qt-vsaddin-msvc2022-3.0.2.vsix"
        Invoke-WebRequest -Uri $url -OutFile $output

    - name: Verify SHA-256 Hash
      run: |
        $expectedHash = "b1eba080495505638e2431e85ffa4108ee3b688595cc4657f1b80e30712c2f23"
        $fileHash = Get-FileHash -Path "qt-vsaddin-msvc2022-3.0.2.vsix" -Algorithm SHA256
        if ($fileHash.Hash -ne $expectedHash) {
          throw "Hash mismatch: $($fileHash.Hash)"
        }

    - name: Find VSIXInstaller
      run: |
        $vsInstallPath = Get-Content $env:GITHUB_ENV | Out-String | Select-String "VS_INSTALL_PATH" | ForEach-Object { $_.ToString().Split("=")[1].Trim() }
        $vsixInstallerPath = Join-Path -Path $vsInstallPath -ChildPath "Common7\IDE\VSIXInstaller.exe"
        if (-Not (Test-Path $vsixInstallerPath)) {
          Write-Error "VSIXInstaller.exe not found."
          exit 1
        }
        Write-Output "VSIX_INSTALLER_PATH=$vsixInstallerPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Install Qt VS Add-in
      run: |
        $vsixInstallerPath = Get-Content $env:GITHUB_ENV | Out-String | Select-String "VSIX_INSTALLER_PATH" | ForEach-Object { $_.ToString().Split("=")[1].Trim() }
        Start-Process -FilePath $vsixInstallerPath -ArgumentList "/q", "qt-vsaddin-msvc2022-3.0.2.vsix" -NoNewWindow -Wait
