name: Hello World CI

on:
  # Trigger CI on push and pull request
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup MSVC (Visual Studio Build Tools)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Install Rust (v1.76)
        run: |
          Invoke-WebRequest -Uri https://static.rust-lang.org/rustup/release/stable/x86_64-pc-windows-msvc/rustup-init.exe -OutFile rustup-init.exe
          Start-Process -FilePath rustup-init.exe -ArgumentList "-y --default-toolchain 1.76.0" -NoNewWindow -Wait
          refreshenv

      - name: Verify Rust Installation
        run: |
          rustc --version
      - name: Build C++ Code
        run: |
          cl /EHsc main.cpp /Fe:main.exe

      - name: List Directory Contents (Debugging)
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
