name: Hello World CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version


      - name: Download Visual Studio Build Tools Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_buildtools.exe

      - name: Install Visual Studio 2022 Build Tools
        shell: cmd
        run: |
          start /wait vs_buildtools.exe --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools

      - name: Find Visual Studio Path
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -version [17.0,18.0) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath > vs_path.txt

      - name: Set up MSVC Environment (x64)
        shell: cmd
        run: |
          set /p vs_path=<vs_path.txt
          if not defined vs_path (exit /b 1)
          call "%vs_path%\VC\Auxiliary\Build\vcvarsall.bat" x64
          set

      - name: Verify `cl` Command
        shell: cmd
        run: |
          cl /?

      - name: Build C++ Code
        shell: cmd
        run: |
          cl /EHsc main.cpp /Fe:main.exe

      - name: List Directory Contents
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
