name: Hello World CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version

      - name: Install CMake
        uses: twilio/cmake-action@v1

      - name: Configure CMake Project
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..

      - name: Build with CMake
        run: |
          cd build
          cmake --build . --config Release

      - name: List Build Directory Contents
        run: |
          dir build\Release

      - name: Run Executable
        run: |
          build\Release\main.exe
