name: Multi-Repository Checkout

on: [push, pull_request]

jobs:
  checkout-repos:
    runs-on: windows-latest  

    steps:

      - name: Checkout OpenTwin repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/OpenTwin'
          path: 'OpenTwin'  # Directory to clone the repository into

      - name: Checkout ThirdParty repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/ThirdParty'
          path: 'ThirdParty'  # Directory to clone the repository into

      - name: Use files from OpenTwin
        run: |
          dir OpenTwin  # Using Windows command 'dir' instead of 'ls'
          # You can now use files from the OpenTwin repository in your workflow

      - name: Use files from ThirdParty
        run: |
          dir ThirdParty  # Using Windows command to list files
          # You can now use files from the ThirdParty repository in your workflow
