name: Setup Visual Studio 2022 Build Tools

on: [push, pull_request]

jobs:
  setup-vs-build-tools:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Chocolatey
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
    - name: Install Visual Studio Build Tools 2022
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.ATL --add Microsoft.VisualStudio.Component.VC.MFC"
        
        # Set environment variable DEVENV_ROOT_2022 to the installation path
        $env:DEVENV_ROOT_2022 = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\VisualStudio\SxS\VS7" -Name "17.0").17.0
        Write-Output "DEVENV_ROOT_2022=$env:DEVENV_ROOT_2022" >> $GITHUB_ENV
        
    - name: Verify installation
      run: |
        # Verify installation by checking if DEVENV_ROOT_2022 is set correctly
        echo "Visual Studio Build Tools 2022 installed at $env:DEVENV_ROOT_2022"
