name: Hello World CI

on:
  # Trigger CI on push and pull request
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version

      - name: Setup MSVC (Visual Studio Build Tools)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build C++ Code
        run: |
          cl /EHsc main.cpp /Fe:main.exe

      - name: List Directory Contents (Debugging)
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
