name: Multi-Repository Checkout

on: [push, pull_request]

jobs:
  checkout-repos:
    runs-on: windows-latest  

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          repository: 'Reeva30/cpp-hello-world'
          token: ${{ secrets.GITHUB_TOKEN }}  
          ref: 'Demo' 

      - name: Checkout OpenTwin repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/OpenTwin'
          path: 'OpenTwin'  # Directory to clone the repository into

      # You can add more repositories as needed

      - name: Use files from OpenTwin
        run: |
          dir OpenTwin  # Using Windows command 'dir' instead of 'ls'
          # You can now use files from the OpenTwin repository in your workflow
