name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Qt VS Add-in using Chocolatey
      run: |
        choco install qt-vsaddin --version=3.0.2 -y

    - name: Verify Qt VS Add-in Installation
      run: |
        $extensionsPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\Extensions"
        Write-Host "Listing contents of the Extensions directory:"
        Get-ChildItem -Path $extensionsPath | Format-Table -AutoSize
        
        $qtVsToolsPath = Join-Path $extensionsPath "Trolltech\\QtVisualStudioTools"
        if (-Not (Test-Path $qtVsToolsPath)) {
          Write-Error "Qt VS Tools not found in Visual Studio extensions."
          exit 1
        }
        Write-Host "Qt VS Tools successfully installed."

    - name: Build Qt Project
      run: |
        $solutionPath = "path\\to\\your\\solution.sln"
        $devenvPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe"
        & $devenvPath $solutionPath /Build
