name: C++ CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install gcc
    - name: Build project
      run: g++ -o hello_world main.cpp
    - name: Run tests
      run: ./hello_world

