name: C++ CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install MSYS2
      run: |
        choco install msys2
        refreshenv
        C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Sy --noconfirm base-devel mingw-w64-x86_64-toolchain"
    - name: Build project
      run: |
        C:\tools\msys64\usr\bin\bash.exe -lc "g++ -o hello_world.exe main.cpp"
    - name: Run tests
      run: |
        hello_world.exe
