name: C++ Build and Test

on:
  push:
    branches:
      - inv

jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Visual Studio 2022 Build Tools using Chocolatey
      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        shell: powershell

      - name: Set up MSBuild path
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe" /?

      - name: Build main.cpp
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe" /t:Build /p:Configuration=Release /p:Platform=x64

      - name: Run the executable
        shell: cmd
        run: |
          .\main.exe
