name: Setup Visual Studio 2022 Build Tools

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2022 Build Tools
      uses: microsoft/vssetup.action/setup@v2
      with:
        installationPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools'
        components: 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64'

    - name: Print Visual Studio 2022 IDE path
      run: |
        echo "Visual Studio 2022 IDE is installed at: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
