

name: C++ CI with Cached Artifacts

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022 Build Tools
      run: |
        choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest"
      shell: cmd

    - name: Install Qt
      run: |
        choco install -y qt-installer
        powershell -command "& {Start-Process -Wait -FilePath 'C:\ProgramData\chocolatey\lib\qt-installer\tools\QtInstaller.exe' -ArgumentList '--platform minimal --script qt-noninteractive.qs'}"
      shell: cmd

    - name: Install VSSetup module and Qt Visual Studio Tools extension
      run: |
        powershell -command "Install-Module -Name VSSetup -Force -AllowClobber"
        powershell -command |
          Import-Module VSSetup
          $vs = Get-VSSetupInstance -All | Where-Object { $_.InstallationPath -ne $null }
          if ($vs) {
            $vsPath = $vs[0].InstallationPath
            Start-Process -FilePath \"$vsPath\Common7\IDE\devenv.exe\" -ArgumentList '/InstallVSPackage','0A5A7800-D8E3-4A6F-85D8-BC8A7B473F24' -Wait
          } else {
            Write-Error 'Visual Studio instance not found'
          }
      shell: powershell


