

name: C++ CI with Cached Artifacts

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022 Build Tools
      run: |
        curl -Lo vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe
        start /wait vs_buildtools.exe --quiet --wait --norestart --nocache \
          --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
          --add Microsoft.VisualStudio.Workload.NativeDesktop \
          --add Microsoft.VisualStudio.Component.Windows10SDK \
          --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest
      shell: cmd

    - name: Install Qt
      run: |
        curl -Lo qt-installer.exe https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
        start /wait qt-installer.exe --script qt-noninteractive.qs
      shell: cmd

    - name: Install VSSetup module and Qt Visual Studio Tools extension
      run: |
        powershell -Command "Install-Module -Name VSSetup -Force -AllowClobber"
        powershell -Command "Import-Module VSSetup"
        powershell -Command "$vs = Get-VSSetupInstance -All | Where-Object { $_.InstallationPath -ne $null }"
        if ($vs -ne $null) {
          $vsPath = $vs[0].InstallationPath
          Start-Process -FilePath "$vsPath\Common7\IDE\devenv.exe" -ArgumentList '/InstallVSPackage','0A5A7800-D8E3-4A6F-85D8-BC8A7B473F24' -Wait
        } else {
          Write-Error "Visual Studio instance not found"
        }
      shell: powershell


