name: Hello World CI

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust and C++ on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version

      - name: Download Visual Studio Build Tools Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_buildtools.exe

      - name: Install Visual Studio 2022 Build Tools
        shell: cmd
        run: |
          start /wait vs_buildtools.exe --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install CMake via Chocolatey
        shell: cmd
        run: |
          choco install cmake --yes

      - name: Build C++ Project Using CMake
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 -B build
          cmake --build build --config Release

      - name: List Directory Contents
        run: |
          dir build

      - name: Run Executable
        run: |
          .\build\Release\main.exe
