name: Hello World CI

on:
  # Trigger CI on push and pull request
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]

jobs:
  build-and-test:
    name: Build, Test, and Install Rust on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version
          
      - name: Install Visual Studio 2022 Build Tools
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_buildtools.exe
          Start-Process -FilePath vs_buildtools.exe -ArgumentList "--quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait

      - name: Verify Visual Studio 2022 Installation
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /?

      - name: Build C++ Code
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc main.cpp /Fe:main.exe


      - name: List Directory Contents (Debugging)
        run: |
          dir

      - name: Run Executable
        run: |
          .\main.exe
