name: Simplified C++ Build and Test

on:
  push:
    branches: [inv]
  pull_request:
    branches: [inv]

jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      # Install Rust (v1.76.0)
      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      # Verify Rust Installation
      - name: Verify Rust Installation
        run: |
          rustc --version

      # Cache CMake for subsequent builds
      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: C:\Program Files\CMake
          key: cmake-${{ runner.os }}

      # Install CMake using Chocolatey if not cached
      - name: Install CMake
        if: steps.CacheCMake.outputs.cache-hit != 'true'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell
      

      # Generate build files using CMake
      - name: Generate Build Files
        run: |
          cmake -B . -S .
          cmake --build . --config Release  # Compile in Release mode

      - name: Run the executable
        run: |
          .\build\main.exe
