name: Pull from separate repo and run build script

on:
  push:
    branches:
      - RunBuild

jobs:
  pull-other-repo:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the main project repository
    - name: Check out the main project repository
      uses: actions/checkout@v2
      with:
        repository: OT-OpenTwin/OpenTwin
        ref: Ci
        path: OpenTwin

    # Step 2: Check out the third-party repository
    - name: Check out the third-party repository
      uses: actions/checkout@v2
      with:
        repository: OT-OpenTwin/ThirdParty
        path: ThirdParty

    # Step 3: Install Visual Studio 2022 Build Tools
    - name: Install Visual Studio 2022 Build Tools
      run: |
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --wait"
      shell: cmd

    # Step 4: Install Rust 1.76.0
    - name: Install Rust 1.76.0
      run: |
        choco install rust --version=1.76.0 -y
      shell: cmd

    # Step 5: Display the files in the main project repository
    - name: List files in the main project repository
      run: dir OpenTwin

    # Step 6: Display the files in the third-party repository
    - name: List files in the third-party repository
      run: dir ThirdParty

    # Step 7: Set environment variables and run the BuildAll.bat script
    - name: Run BuildAll.bat and capture log
      run: |
        cd OpenTwin
        echo "Current directory: %cd%"
        set OPENTWIN_DEV_ROOT=%cd%
        set OPENTWIN_THIRDPARTY_ROOT=%cd%\..\ThirdParty
        set DEVENV_ROOT_2022="C:\Program Files\Microsoft Visual Studio\2022\BuildTools"
        .\Scripts\BuildAndTest\BuildAll.bat > build.log 2>&1
      shell: cmd

    # Step 8: Upload build log artifact
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: OpenTwin\build.log
