name: Build and Test C++ Project

on:
  push:
    branches:
      - Demo  # Adjust the branch as needed

jobs:
  setup-environment:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout OpenTwin repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/OpenTwin'
          path: 'OpenTwin'  # Directory to clone the repository into

      - name: Set up Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest"

      - name: Install CMake
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Install Rust
        run: |
          choco install -y rust --version=1.76.0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'  # Adjust to match Visual Studio 2022 if necessary
          modules: 'qtbase,qttools'  # Specify the required Qt modules

  build-and-test:
    runs-on: windows-latest
    needs: setup-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout OpenTwin repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/OpenTwin'
          path: 'OpenTwin'  # Directory to clone the repository into



      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: |
            build
          key: ${{ runner.os }}-cmake-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-build-

      - name: Set up Visual Studio Build Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Generate Build Files with CMake
        run: |
          cmake -B build -S .

      - name: Build Project
        run: |
          cmake --build build --config Release

      - name: Check Build Artifact Size
        run: |
          du -sh build

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Upload build artifacts to S3
        run: |
          aws s3 cp build s3://${{ secrets.S3_BUCKET_NAME }}/build --recursive

  test:
    runs-on: windows-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout OpenTwin repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/OpenTwin'
          path: 'OpenTwin'  # Directory to clone the repository into

      - name: Checkout ThirdParty repository
        uses: actions/checkout@v2
        with:
          repository: 'OT-OpenTwin/ThirdParty'
          path: 'ThirdParty'  # Directory to clone the repository into

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build
