name: Install Qt VS Add-in and Build Qt Project

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Download and Extract Qt VS Add-in
      run: |
        $url = "https://mirror.netcologne.de/qtproject/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix"
        $output = "qt-vsaddin-msvc2022-3.0.2.vsix"
        Invoke-WebRequest -Uri $url -OutFile $output
        $expectedHash = "b1eba080495505638e2431e85ffa4108ee3b688595cc4657f1b80e30712c2f23"
        $fileHash = Get-FileHash -Path $output -Algorithm SHA256
        if ($fileHash.Hash -ne $expectedHash) {
          throw "Hash mismatch: $($fileHash.Hash)"
        }
        Expand-Archive -Path $output -DestinationPath "qt-vsaddin"

    - name: Copy Qt VS Add-in to Extensions Directory
      run: |
        $extensionsPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\Extensions"
        $qtVsToolsPath = Join-Path $extensionsPath "Trolltech\\QtVisualStudioTools"
        if (Test-Path $qtVsToolsPath) {
          Remove-Item -Path $qtVsToolsPath -Recurse -Force
        }
        New-Item -Path $qtVsToolsPath -ItemType Directory
        Copy-Item -Path "qt-vsaddin\\*" -Destination $qtVsToolsPath -Recurse

    - name: Verify Qt VS Add-in Installation
      run: |
        $extensionsPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\Extensions\\Trolltech\\QtVisualStudioTools"
        Write-Host "Listing contents of the Extensions directory:"
        Get-ChildItem -Path $extensionsPath | Format-Table -AutoSize
        
        $qtVsToolsPath = Join-Path $extensionsPath "Trolltech\\QtVisualStudioTools"
        if (-Not (Test-Path $qtVsToolsPath)) {
          Write-Error "Qt VS Tools not found in Visual Studio extensions."
          exit 1
        }
        Write-Host "Qt VS Tools successfully installed."

    - name: Build Qt Project
      run: |
        $solutionPath = "path\\to\\your\\solution.sln"
        $devenvPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe"
        & $devenvPath $solutionPath /Build
