name: C++ Build and Test

on:
  push:
    branches:
      - inv

jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Visual Studio 2022 Build Tools using Chocolatey
      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        shell: powershell

      # Set up the Visual Studio command-line environment
      - name: Set up Visual Studio Build Environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      # Compile main.cpp using the cl compiler
      - name: Compile main.cpp
        shell: cmd
        run: |
          cl /EHsc /Fe:main.exe main.cpp

      # Run the executable
      - name: Run the executable
        shell: cmd
        run: |
          .\main.exe
