name: C++ Build and Test

on:
  push:
    branches: [ inv ]
  pull_request:
    branches: [ inv ]


jobs:
  build:
    name: Build C++ Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust (v1.76.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          override: true

      - name: Verify Rust Installation
        run: |
          rustc --version

      # Install CMake using Chocolatey
      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell

      # Install Visual Studio 2022 Build Tools
      - name: Install Visual Studio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        shell: powershell
        
     # Download and Install Qt
      - name: Download and Install Qt
        run: |
          # Download the Qt installer
          Invoke-WebRequest -Uri "https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe" -OutFile "qt-installer.exe"
          # Install Qt using silent installation
          Start-Process -FilePath "qt-installer.exe" -ArgumentList '--silent --default-answer --platform minimal --root C:\Qt --qt-path 5.15.2\msvc2019_64' -NoNewWindow -Wait
        shell: powershell

        
      # Set up Visual Studio command-line environment
      - name: Set up Visual Studio Build Environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      # Ensure that the -S (source) flag points to the root (or subdirectory with CMakeLists.txt)
      - name: Generate Build Files
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH="C:\Qt\5.15.2\msvc2019_64"

      # Ensure the build folder is correct
      - name: Build Project
        run: |
          cmake --build build --config Release


      # Run the executable
      - name: Run the executable
        run: |
          .\build\Release\main.exe
